### ISSUE TITLE
SampleShadowCascade applies offset and scale in wrong order (?)

### ISSUE THREAD

**Issue by sbd1138** [TheRealMJP/Shadows#4]
In SampleShadowCascade in Mesh.hlsl, when computing the shadow position of the receiving pixel, I believe you should be applying the cascade scale first, then adding the offset.

```
    shadowPosition += CascadeOffsets[cascadeIdx].xyz;
    shadowPosition *= CascadeScales[cascadeIdx].xyz;

```
should be

    shadowPosition *= CascadeScales[cascadeIdx].xyz;
    shadowPosition += CascadeOffsets[cascadeIdx].xyz;

Purely mathematically speaking, if we think of applying this as a matrix, the latter is the proper order.  Of course, depending on the values, these can produce drastically different results.  But perhaps in this particular sample's use-case, the difference is not noticeable.  Most other samples (like the DX SDK CascadedShadowMap sample) apply these in scale then offset order.

**Comment by TheRealMJP** [comment]
Hey! There's not really a "right" or "wrong" order to apply the scale and offset here, you just have to make sure you're consistent about it. Scaling after translation or rotation is totally valid mathematically speaking, it's just not traditionally done that way when forming the transformation for a single object/mesh/etc. since it can be more intuitive to have scale happen according to the local object-space origin rather than after being translated or rotated. But even with a traditional setup you can create a scale-after-translate situation easily in a scene hierarchy like you have in Maya or Blender: it happens when you have a node with scale and then you parent another node with a translation.

In the case of this app "being consistent" means that the scale and offsetting in the shader code has to match the cascade setup code being done on the CPU. If you look at the [relevant code](https://github.com/TheRealMJP/Shadows/blob/master/Shadows/MeshRenderer.cpp#L1542) it's calculating the scale using the cascade corners that already have the offset/translation applied to them. If you were to flip the order of the scale/offset in the shader code then you would have to undo the offset to cascade corners first and then calculate the scale factor, so that the scale is calculated in the "non-offset" space. I haven't looked at the DX sample in a long time but I imagine it's doing it that way, which is why their scale/offset are applied in a different order. I could see an argument for the code being a bit easier to understand if the scale is applied first to match the typical ordering of a full transform matrix, but that's more of a style issue IMO.

**Comment by sbd1138** [comment]
Thanks for the reply!  Indeed, consistency is the correct lense to view this through.  In the case of the DX sample, it's extracting the offset and scale from the final composed cascade projection matrix (as am I), which itself was constructed in scale->offset order.  I didn't scrutinize the offset/scale calculation code as closely as I should have, I was thinking purely in terms of it coming from a projection matrix constructed in a particular way.
