### ISSUE TITLE
Stabilize shadow becomes shimmering when increasing shadow range?

### ISSUE THREAD

**Issue by JiaoJianing** [TheRealMJP/Shadows#6]
Hi,
I recently worked on 'stable csm' , and then found this repo. Really thanks for your work!
Everything works well when using default config(with nearclip 0.25 and farclip 250), with checking 'Stabilize Cascades'.
But when changing farclip to 1000,  some shimmering appear like below:

https://github.com/TheRealMJP/Shadows/assets/12868409/795731b3-c410-4e7d-b980-d8307ea32078

Is this caused by precision problem or something else? I also tested in Unreal Engine 4.27 with a distance of 50km and 5 cascades, it seems still stable. I do not know what is the key tech. Since our render scene is an outdoor scenario, I wish my shadow can cover 10km or more distance.

Looking forward to your reply!

**Comment by TheRealMJP** [comment]
Hey there, I would guess that there is indeed some sort of precision issue when either generating or applying the shadow matrices in `MeshRenderer::RenderShadowMap`. I did not test it with larger far clip values, so I'm not surprised that there's some issues. I'm also not familiar with how UE sets up their cascades, but I wouldn't be surprised if they had taken more care to have the code work correctly with larger values. 

If I get a chance I'll to see if I can see where things are going wrong, but I may not have some time to do that for a while. In the meantime, if you figure out anything on your end I would appreciate if you let me know what the problem was.

**Comment by TheRealMJP** [comment]
Ok I was actually able to spot and fix the problem pretty quickly, with my latest commit it was still stable with the far clip set to 50k.
